name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
          
      - name: Install dependences
        run: yarn
        
      - name: Run build
        run: yarn build
        
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist"
          target: "test"

    # Instalar as dependencias NPM/yarn
    # Executar a build
    # Copiar pasta dist para dentro do servidor
      
    #Substituir o código existente na pasta "dist" pelo novo código
    # Executar "yarn" no Servidor
    # Executar as migrations do Typeorm
    # Restartar no servidor NodeJS
